package dhbw.swe.valueobjects;

public enum Qualification {
    JAVA, PYTHON, GO, JAVASCRIPT, RUST, TEAM_LEADERSHIP, DATA_ANALYSIS, AI_ML, PROJECT_MANAGEMENT, SCRUM_MASTER, REQUIREMENTS_ENGINEERING, SOFTWARE_ARCHITECTURE, TESTING, DEVOPS, DATABASE_ADMINISTRATION, UI_DESIGN
}
